name: Step Templates
description: Allows steps to be injected into the pipeline based on a common template.
author: https://github.com/jamestelfer
requirements: []
configuration:
  properties:
    step-template:
      type: string
    step-var-names:
      type: array
    auto-selections:
      type: array
    selector-template:
      type: string
    require-up-to-date:
      type: object
      properties:
        enabled:
          type: boolean
          default: false
        branch:
          type: string
          default: "main"
        must-be-branch-head:
          type: boolean
          default: false
        fail-mode:
          type: string
          enum: ["hard", "soft"]
          default: "hard"
      additionalProperties: false
  additionalProperties: false