#!/usr/bin/env bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"
# shellcheck source=lib/steps.bash
. "$DIR/../lib/steps.bash"

step_template="$(plugin_read_config "TEMPLATE")"
selector_template="$(plugin_read_config "SELECTOR")"

step_var_names="$(plugin_read_list "STEP_VAR_NAMES")"

auto_selections="$(plugin_read_list "AUTO_SELECTIONS")"

if [[ -z "$step_template" ]] ; then
  echo "+++ ❌ Step templates plugin error"
  echo "No 'step_template' argument provided: cannot produce pipeline fragments without the template."
  exit 1
fi

if [[ -z "$selector_template" ]]  && [[ -z ${#auto_selections[@]} ]] ; then
  echo "+++ ❌ Step templates plugin error"
  echo "Neither selector_template nor auto_selections specified: nothing to do."
  exit 1
fi

# does the template exist?

# reverse order

# selector_template
if [[ "${SELECTOR:-}" = "true" ]]; then
  # The block step will appear last
  buildkite-agent pipeline upload .buildkite/deploy-selector.yml
fi

# auto-selections
# if [[ -z "$selected_environments" ]]; then
#   selected_environments=$(buildkite-agent meta-data get "deploy-environment" --default "")
# fi


write_steps "${step_template}" "${step_var_names}" "${auto_selections}"
